### PR TITLE
use_single_float

### PR DESCRIPTION
**Pull request by fab13n**
Proposal to allow forcing float packing as single precision.

### CODE REVIEW

**Comment by vsergeev** [comment]
I was ready to merge, but then I got a little concerned by what this parameter should do if it's `False` and on a 32-bit float platform.

So far we've got:
* 64-bit platform float, `use_single_float` `True` -> 32-bit float
* 64-bit platform float, `use_single_float` `False` -> 64-bit float
* 32-bit platform float, `use_single_float` `True` -> 32-bit float
* 32-bit platform float, `use_single_float` `False` -> ? 64-bit float?

We could also do `use_float_size` = `32`/`64` or `use_float_precision` `single`/`double`, but those are not as convenient as booleans.

**Comment by vsergeev** [comment]
After some more discussion with a friend, I think `force_single_float` or `force_float32` would resolve any ambiguity.

**Comment by fab13n** [comment]
Here "single" and"double" refer to precision as defined by IEEE754, not the
machine word-size, so I don't think there's any ambiguity: single always
means 32 bits, and double always means 64 bits. In practice, double
precision floats are the de facto default.

BTW, there's a possible further improvement: in the default mode: encode
floats as singles if (double)(float) x == (double) x. This would save 4
bytes without reducing precision. Then indeed, the option to use single
floats even if it affects precision should be called "force_single_float".

**Comment by vsergeev** [comment]
By 32-bit platform float, I just meant the float size determined from [`sys.float_info`](https://docs.python.org/3.6/library/sys.html#sys.float_info), e.g. if Python was built with a single or double precision float data type.

The ambiguity is the meaning of `use_single_float` is on a single-precision float Python environment. If the option is false, the current implementation will still use a single-precision float. But I think the intention of your change is to force a single precision float to save space, so maybe "force" is a better word than "use".

The automatic precision detection is intriguing, but I don't know of a clean way to express that in Python without using ctypes or some struct magic, which sounds fairly expensive.

**Comment by vsergeev** [comment]
I squashed and modified your commits to implement `force_float_precision` = `"single"` or `"double"`. Let me know what you think.

**Comment by fab13n** [comment]
Good for me.You plan to put it in a release soon?

**Comment by vsergeev** [comment]
Yup, just gotta update the changelog. 24 hours.

**Pull request closed without merging**
